### ISSUE TITLE
Allow drag to open in finder toolbar

### ISSUE THREAD

**Issue by danejordan** [getcursor/cursor#1220] opened 2024-02-04 22:03 UTC
**Is your feature request related to a problem? Please describe.**
Allow drag and drop cursor opening in finder toolbar

**Describe the solution you'd like**
Drag a file / folder from finder onto the cursor icon in the toolbar to open repo / file with cursor

https://github.com/getcursor/cursor/assets/10985108/89813a88-e0e0-4ff7-8668-7eefba608498

**Comment by danperks** [comment] 2024-10-02 19:37
Duplicate of #586

**Closed** 2024-10-02 19:38 UTC

**Comment by stevensiweix** [comment] 2024-12-15 00:40
我也很需要這個功能，再請開發團隊加油了～
