### ISSUE TITLE
Support the upload of PDF documents

### ISSUE THREAD

**Issue by Am0stafa** [getcursor/cursor#1622] opened 2024-08-11 19:36 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**

**Comment by Am0stafa** [comment] 2024-08-11 19:36
PDFs are currently ignored

**Comment by danperks** [comment] 2024-09-24 21:21
Duplicate of #1894

**Closed by danperks** 2024-09-24 21:21 UTC
