### ISSUE TITLE
typescript language server constant crashing

### ISSUE THREAD

**Issue by rickco75** [getcursor/cursor#2028] opened 2024-09-29 13:36 UTC
Type: <b>Bug</b>

typescript server keeps crashing then won't start

VS Code version: Cursor 0.41.3 (51c8aff7cb5a89f4a0e462fbacab938bdbfaf140, 2024-09-25T17:13:50.377Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 5.15.153.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 7940HS w/ Radeon 780M Graphics      (16 x 3992)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|61.73GB (33.01GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.153.1-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 9 7940HS w/ Radeon 780M Graphics (16 x 0)|
|Memory (System)|30.23GB (26.40GB free)|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
graphql|mqu|0.1.2
remote-containers|ms-|0.327.0
remote-wsl|ms-|0.81.8
sqlite-viewer|qwt|0.7.2
vscode-docker|ms-|1.29.2

</details>

**Comment by danperks** [comment] 2024-10-02 19:41
Duplicate of #1888

**Closed** 2024-10-02 19:41 UTC
