### ISSUE TITLE
Initializing Cursor sh but immediately encountering fatal sandbox error

### ISSUE THREAD

**Issue by axellee1994** [getcursor/cursor#1483] opened 2024-06-08 01:09 UTC
![Screenshot from 2024-06-08 09-06-18](https://github.com/getcursor/cursor/assets/124663345/0fc8096c-f728-45f6-9c44-551170d0c9d0)

Version: Linux 24.04

**Comment by 0xlidar** [comment] 2024-07-08 08:59
Related issue: #1465

**Comment by Livia-Zaharia** [comment] 2024-09-16 13:27
It is caused by messed up pemissions in AppImage, my workaround is https://github.com/getcursor/cursor/issues/1907

**Comment by danperks** [comment] 2024-09-18 13:41
Closing as a duplicate in favour of #1465 to keep discussions in one thread, however a workaround is posted in #1907 that you may be able to try

**Closed by danperks** 2024-09-18 13:41 UTC
