### ISSUE TITLE
Open folder by drag and drop 

### ISSUE THREAD

**Issue by Hitesh-Sisara** [getcursor/cursor#1329] opened 2024-03-19 05:32 UTC
**Describe the solution you'd like**
Users should be able to drag and drop folders onto the app's Dock icon to open projects directly 

since vs code have this feature Adding this to Cursor would be helpful because many developers are used to it 

https://github.com/getcursor/cursor/assets/72780174/c4f264ab-f553-46f7-8ce5-d979d122daf2

**Comment by lspoor** [comment] 2024-09-16 09:30
+1 here, sounds small but its found it incredibly frustrating now I've lost this functionality

**Comment by Nicolas-nwb** [comment] 2024-09-23 13:02
It's crazy that so few people have come forward about this request. When working on multiple projects, this is a feature that is sorely missing. It would be great for the Cursor team to look into this feature, which is probably simpler to develop than many things in Cursor.

**Comment by lukecharle** [comment] 2024-09-23 13:11
I've noticed we can drag/drop files, but just not folders :(

**Comment by danperks** [comment] 2024-10-02 19:38
Duplicate of #586

**Closed by danperks** 2024-10-02 19:38 UTC
