### ISSUE TITLE
Composer cannot write markdown.

### ISSUE THREAD

**Issue by stobias123** [getcursor/cursor#1851] opened 2024-09-08 20:29 UTC
When working with composer, sometimes I want to take some intermediate steps. 

For example, I might brainstorm some and prompt to create/refine a tech spec. I want composer to write this to a file "spec.md". 

The composer will often start writing this file either in the chat window, or to file, and then it appears to escape it's current output directory, and finish writing the spec into the chat window, but unformatted.

**Comment by TonyGiorgio** [comment] 2024-09-10 16:08
I think this is a duplicate of this: https://github.com/getcursor/cursor/issues/1705

**Comment by danperks** [comment] 2024-09-19 17:22
Duplicate of #1705 as mentioned by @TonyGiorgio

**Closed by danperks** 2024-09-19 17:22 UTC
