### ISSUE TITLE
can't run on unbuntu 18

### ISSUE THREAD

**Issue by hanwsf** [getcursor/cursor#78] opened 2023-03-18 09:21 UTC
run in terminal shows some files missing

**Comment by hanwsf** [comment] 2023-03-18 10:33
./Cursor-0.1.1.AppImage
innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /tmp/.mount_Cursorzd4V2P/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js
- /tmp/.mount_Cursorzd4V2P/resources/app.asar/node_modules/node-pty/lib/index.js
- /tmp/.mount_Cursorzd4V2P/resources/app.asar/.webpack/main/index.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:963:15)
    at n._resolveFilename (node:electron/js2c/browser_init:2:109416)
    at Module._load (node:internal/modules/cjs/loader:811:27)
    at f._load (node:electron/js2c/asar_bundle:2:13328)
    at Module.require (node:internal/modules/cjs/loader:1035:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/tmp/.mount_Cursorzd4V2P/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:30:15)
    at Module._compile (node:internal/modules/cjs/loader:1141:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1196:10)
    at Module.load (node:internal/modules/cjs/loader:1011:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/tmp/.mount_Cursorzd4V2P/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js',
    '/tmp/.mount_Cursorzd4V2P/resources/app.asar/node_modules/node-pty/lib/index.js',
    '/tmp/.mount_Cursorzd4V2P/resources/app.asar/.webpack/main/index.js',
    undefined
  ]
}
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/.mount_Cursorzd4V2P/resources/app.asar.unpacked/node_modules/node-pty/build/Release/pty.node)
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
    at Module._extensions..node (node:internal/modules/cjs/loader:1226:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:2049)
    at Module.load (node:internal/modules/cjs/loader:1011:32)
    at Module._load (node:internal/modules/cjs/loader:846:12)
    at f._load (node:electron/js2c/asar_bundle:2:13328)
    at Module.require (node:internal/modules/cjs/loader:1035:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/tmp/.mount_Cursorzd4V2P/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:26:11)
    at Module._compile (node:internal/modules/cjs/loader:1141:14)

**Comment by tianxiang1989** [comment] 2023-03-23 03:46
the root cause is the latest node need glibc2.28 but the Ubuntu 18 only includes glic2.27.

> $ strings /lib/x86_64-linux-gnu/libm.so.6 | grep GLIBC_
GLIBC_2.2.5
GLIBC_2.4
GLIBC_2.15
GLIBC_2.18
GLIBC_2.23
GLIBC_2.24
GLIBC_2.25
GLIBC_2.26
GLIBC_2.27
GLIBC_PRIVATE

Solution: 1. upgrade glibc to glic2.28+. Not recommended, you may encounter some error message "core segmentfault".
Solution 2: upgrade Ubuntu 18 to 20.

**Comment by truell20** [comment] 2023-04-08 07:15
think this is fixed in the new version? feel free to reopen / or @ me here if it isnt

**Closed by truell20** 2023-04-08 07:15 UTC
