### ISSUE TITLE
Request for Refund [Saved]

### ISSUE THREAD

**Issue by apptcom1123** [getcursor/cursor#1217] opened 2024-02-02 18:24 UTC
Dear Customer Service Team,

I am writing to request a refund for my recent purchase. I have encountered several issues while using the Cursor software and would appreciate your assistance.

Firstly, I experienced difficulty in accessing my Anaconda environment when remotely connecting to a server through the ipynb files, although this was not an issue when using VSCode. Additionally, I encountered encoding problems in the ipynb files, rendering them unusable. The error happened after I run a code but it worked fine several times. Furthermore, I discovered that my previous chat history had been inexplicably deleted, which has been quite frustrating. Because I have spend three days to complete the code. As a result, I believe that using ChatGPT4 directly may be a more suitable option for me.

In addition to these issues, I have also encountered a problem with the chat feature. I am unable to copy text from the chat messages, which has been inconvenient for me.

Given these issues, I would like to request a refund. My account is registered under bzw1123@gmail.com, and I recently purchased a one-year subscription. However, as the software's functionality did not meet my expectations, I would like to proceed with the refund process.

**Comment by ayyneya** [comment] 2024-02-03 16:36
Written with AI

**Comment by apptcom1123** [comment] 2024-02-04 02:32
> Written with AI

yes, written with cursor, but that is true happened on me.

**Comment by truell20** [comment] 2024-02-04 21:36
Refund sent! Let me know if it doesn't show up within a week.

> In addition to these issues, I have also encountered a problem with the chat feature. I am unable to copy text from the chat messages, which has been inconvenient for me.

Any steps to reproduce? How are you copying text? What platform are you on?

**Comment by Aubermean** [comment] 2024-02-07 20:30
> Refund sent! Let me know if it doesn't show up within a week.
> 
> > In addition to these issues, I have also encountered a problem with the chat feature. I am unable to copy text from the chat messages, which has been inconvenient for me.
> 
> Any steps to reproduce? How are you copying text? What platform are you on?

It's really annoying on macOS. Its hard to highlight the text of a message, unlike in codeblocks where its easy. Being able to right click any message to copy text would be awesome, even better if it can copy maintaining original formatting (markdown etc.).

**Comment by apptcom1123** [comment] 2024-02-09 18:28
> Refund sent! Let me know if it doesn't show up within a week.
> 
> > In addition to these issues, I have also encountered a problem with the chat feature. I am unable to copy text from the chat messages, which has been inconvenient for me.
> 
> Any steps to reproduce? How are you copying text? What platform are you on?



> Refund sent! Let me know if it doesn't show up within a week.
> 
> > In addition to these issues, I have also encountered a problem with the chat feature. I am unable to copy text from the chat messages, which has been inconvenient for me.
> 
> Any steps to reproduce? How are you copying text? What platform are you on?

The situation is as follows: I saw someone using Cursor online and it seemed quite useful, so I decided to give it a try and used it to write a website. The experience was quite good at the time, so I made a purchase.

However, when I used Cursor to connect to the school server and write some code for a research project, things didn't go as smoothly. The advantage of being able to modify code with Cursor couldn't be utilized well. More importantly, when I use Vscode Insider, I can use the conda command to create environments, and my conda environment is accessible within ipynb files, but for some reason, this step becomes very difficult with Cursor. I tried many methods and ended up only using the system's default settings, which was a bit inconvenient.

Strangely, the code I spent two days writing in ipynb (mainly for converting some geographical data into videos) turned into an error file after a crash, with the most critical parts turning into nulnulnul, which was quite frustrating because I had a meeting with my professor the next day.

Then, when I clicked on (Previous Chats) trying to find past records, I found that only the records from six hours ago remained. This made me very sad, so I decided to request a refund QAQ.

Additionally, there's a minor issue. I'm using Windows 11, and of course, during the process, I needed to be able to copy and paste (CTRL+C/CTRL+V) some formulas. I'm Taiwanese, so my English isn't very good, and I often need to translate when reading papers. But it turns out I couldn't copy and paste some of the information I needed using (CTRL+C/CTRL+V) or right-clicking with the mouse.

Moreover, it would be great if the CHAT could have a zoom in/out feature. Sometimes the text is really too small~~

In summary, thank you for your reply, I'm very happy. But so far, I haven't seen an email about the refund application sent to bzw1123@gmail.com.

**Comment by apptcom1123** [comment] 2024-02-13 11:22
> it doesn't show up within a week.

It still doesn't show up in my email.

**Comment by apptcom1123** [comment] 2024-02-15 03:39
> It still doesn't show up in my email.

It still doesn't show up in my email.

**Comment by thisislvca** [comment] 2024-02-17 10:52
It takes a sec to process payments, cmon :)

**Comment by apptcom1123** [comment] 2024-02-18 22:25
> It takes a sec to process payments, cmon :)

Refund received! thank you very much!!

**Comment by thisislvca** [comment] 2024-02-18 23:13
> Refund received! thank you very much!!

Great to hear! Feel free to close the issue 🙌

**Closed** 2024-03-03 14:19 UTC

**Comment by Paxx2303** [comment] 2024-10-28 09:46
Dear Customer Service Team,

I am writing to request a refund for my recent purchase. I have encountered several issues while using the Cursor software and would appreciate your assistance.

Firstly, I experienced difficulty in accessing my Anaconda environment when remotely connecting to a server through the ipynb files, although this was not an issue when using VSCode. Additionally, I encountered encoding problems in the ipynb files, rendering them unusable. The error happened after I run a code but it worked fine several times. Furthermore, I discovered that my previous chat history had been inexplicably deleted, which has been quite frustrating. Because I have spend three days to complete the code. As a result, I believe that using ChatGPT4 directly may be a more suitable option for me.

In addition to these issues, I have also encountered a problem with the chat feature. I am unable to copy text from the chat messages, which has been inconvenient for me.

Given these issues, I would like to request a refund. My account is registered under [namnguyen230304@gmail.com](mailto:bzw1123@gmail.com), and I recently purchased a one-year subscription. However, as the software's functionality did not meet my expectations, I would like to proceed with the refund process.

**Comment by patils-aditya** [comment] 2025-07-23 09:06
Subject: Request for Refund and Assistance with Cursor App Issues

Hello Cursor Team,

I hope you’re doing well. I’ve been a committed user of Cursor for over 6 months now, and I truly value the experience and support the platform offers for developers.

I’m writing to request your help with a few ongoing issues that have affected my workflow:

1.Missing Chat History:
After a recent update, I’ve been unable to view my previous chat history within the code editor. These past interactions are important to me for reviewing earlier suggestions and understanding changes over time.

2.Index Rebuilding Repeatedly:
I’ve noticed the editor sometimes rebuilds the index from start to end multiple times, which interrupts the flow and slightly affects the quality of code generation.

3.Duplicate Billing Concern:
I also noticed that two charges were made to my account recently. Since I hadn’t expected these, I kindly request a refund for the recent duplicate payment.

I genuinely appreciate the work your team is doing, and I’m hopeful these concerns can be addressed. Please let me know if you need any additional information. My account email is work.neurashastraai@gmail.com.

Thank you for your time, understanding, and continued support.

Warm regards,
Aditya Patil
