### ISSUE TITLE
Cannot drag and drop folder onto the Dock icon to open it in Cursor

### ISSUE THREAD

**Issue by xilopaint** [getcursor/cursor#989] opened 2023-10-12 17:34 UTC
It's currently working with files but not with folders.

* Cursor 0.12.3
* macOS 14.0.0

**Comment by alexander-cato** [comment] 2023-11-09 21:30
Cursor: 0.14.0 
Not working with files or folders.

**Comment by xilopaint** [comment] 2023-11-09 21:47
> Cursor: 0.14.0 Not working with files or folders.

It still works with files for me in 0.14.0.

**Comment by alexander-cato** [comment] 2023-11-09 22:12
Ah, you are correct, it is working for me with most file extensions. However, specifically .txt files will not allow drag and drop.

**Comment by shuhei-fujita** [comment] 2023-11-16 01:06
>Not working with files or folders.

I finded too🤔

**Comment by tianrendong** [comment] 2023-11-24 16:01
I find the lack of drag and drop feature a crucial roadblock to transitioning fully to cursor from vscode. Hope this gets prioritized more. Thanks!

**Comment by shuhei-fujita** [comment] 2023-11-25 08:06
Cursor is a fork project of Visual Studio Code (VSCode). VSCode supports drag-and-drop functionality, enabling users to directly open local folders within the IDE.

The implementation of this feature appears to be in the code within the src/vs/workbench/browser/dnd.ts file at the following URL, which processes drag-and-drop events and handles the opening of folders🤔

https://github.com/microsoft/vscode/blob/main/src/vs/workbench/browser/dnd.ts#L100-L118

**Comment by akagaeng** [comment] 2024-07-22 03:34
It still doesn’t work in version 0.37.1. 
This small change could have a big impact. 
I hope it’s implemented soon.

**Comment by trenkwill** [comment] 2024-07-30 13:26
yep one of the reasons I'm not using Cursor right now

**Comment by drdDavi** [comment] 2024-08-28 02:14
The cursor team, are removing core quality of life feature from vscode, all we want is the same functionalities as vscode with the AI, please stop removing core features.

**Comment by li986390329** [comment] 2024-09-13 10:20
version 0.40.0 ,  still not working.

**Comment by danperks** [comment] 2024-10-02 19:37
Duplicate of #586

**Closed by danperks** 2024-10-02 19:37 UTC
