### ISSUE TITLE
Show internal error when try to chat

### ISSUE THREAD

**Issue by GreyElec** [getcursor/cursor#571] opened 2023-05-05 11:38 UTC
I had a problem using the chat function, there is a window popup about the internal error but not sure how to fix it. Please help.
![image](https://user-images.githubusercontent.com/33427038/236448050-a498d354-c1ab-4a7d-b063-4e838322140a.png)

Version: 0.2.9
Commit: 2724f60a1f74ead43103e0db6f56647eb47e2d7b
Date: 2023-05-05T03:04:05.549Z
Electron: 19.1.9
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No

**Comment by lpbottle** [comment] 2023-05-05 13:46
I have the same problem.

**Comment by lpbottle** [comment] 2023-05-05 13:49
> I have the same problem.

Version: 0.2.9
Version: 2724f60a1f74ead43103e0db6f56647eb47e2d7b
Version: 2023-05-05T03:04:05.549Z
Electron: 19.1.9
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 22.2.0
Sandboxed: No

**Comment by Aaronsound** [comment] 2023-05-05 16:27
I got the same error
![QQ截图20230506002614](https://user-images.githubusercontent.com/53635077/236514122-85054e76-bf43-4496-a7ca-ce3f488dcc42.png)

**Comment by ILZZY** [comment] 2023-05-06 02:12
I got the same error for Mac os

**Comment by UnicornForU** [comment] 2023-05-06 03:50
![image](https://user-images.githubusercontent.com/131330132/236598195-deb2145c-4e3a-4d0a-aee8-bcc14feea2a3.png)
我也是一样的问题

**Comment by EricKengObscure** [comment] 2023-05-06 06:21
> I got the same error for Mac os

+1

**Comment by oddrookie** [comment] 2023-05-06 06:47
I've got the same error, I have no idea to deal with this problem...

**Comment by Supermomomo** [comment] 2023-05-06 07:07
I got the same error windows

**Comment by cai2000** [comment] 2023-05-06 07:18
I got the same error for Windows os. Reinstall the version before 0.2.9 and choose not to update to version 0.2.9, and I can use cursor normally again.

**Comment by gaotingkai** [comment] 2023-05-06 07:47
+1

**Comment by yanzzchn** [comment] 2023-05-06 10:45
+1

**Comment by bullitart** [comment] 2023-05-06 12:01
+1

**Comment by danperks** [comment] 2023-05-16 08:51
Is this still occuring? Maybe reinstall the latest version from https://cursor.so and see if anyone still have issues.

**Comment by danperks** [comment] 2023-05-16 08:54
I'm assuming this was a server error at the time, as the issue is no longer being reported.
I'll close this for now, but if anyone still has this issue, I'll happily reopen it.

**Closed by danperks** 2023-05-16 08:54 UTC
Labels: bug
