### ISSUE TITLE
Support multiple deployments for azure-OpenAI

### ISSUE THREAD

**Issue by alkampfergit** [getcursor/cursor#1927] opened 2024-09-19 06:55 UTC
**Is your feature request related to a problem? Please describe.**
Actually we can specify only one deployment for azure OpenAI, so we can use only one from GPT-4o GPT-4omini etc.

**Describe the solution you'd like**

- Allowing for a Comma Separated list of deployment in the configuration to specify multiple deployment
- Also I'd like to know in the chat when I'm using model from azure. It would be nice if the model name is called azure-{deploymentname} so we can immediately spot which deployment we are using.

**Comment by danperks** [comment] 2024-09-19 10:06
Duplicate of #1922

**Closed by danperks** 2024-09-19 10:06 UTC
