### ISSUE TITLE
Drag and drop a folder on the cursor dock icon should open that folder in Cursor

### ISSUE THREAD

**Issue by VictorMustin** [getcursor/cursor#1441] opened 2024-05-09 03:22 UTC
OS : MacOS (I don't know if it's a common ux pattern in windows)
Just a small quality of life feature. I used to do that a lot in vscode and I miss it.

**Comment by drdDavi** [comment] 2024-08-28 02:15
+1

**Comment by danperks** [comment] 2024-10-02 19:38
Duplicate of #586

**Closed by danperks** 2024-10-02 19:38 UTC
