### ISSUE TITLE
Can't use the Enter key properly

### ISSUE THREAD

**Issue by Clearzero22** [getcursor/cursor#480] opened 2023-04-08 03:55 UTC

**Comment by truell20** [comment] 2023-04-08 06:41
Could you send a screenshot? Where are you having problems using the enter key?

**Comment by Clearzero22** [comment] 2023-04-08 08:13
![image](https://user-images.githubusercontent.com/90132829/230711128-2d1873fe-5be7-4542-8ae2-7bb939eea70d.png)
When I want to enter to change a line in the editor, it doesn't change the line, the cursor stays on the same line and doesn't change the line after pressing the enter key

**Comment by truell20** [comment] 2023-04-10 06:29
This is so odd. Having trouble reproducing on my end. What operating system are you on?

**Comment by Clearzero22** [comment] 2023-04-10 07:14
> 这太奇怪了。在我这边无法重现。你在什么操作系统上？
![image](https://user-images.githubusercontent.com/90132829/230848106-b98b1403-5765-4a76-a310-b6dc256dcfa4.png)
On windows I tried to reinstall and it still does it

**Comment by danperks** [comment] 2023-04-10 09:25
Does your enter key work else where on your operating system as it should? Have you checked your key-binds in Cursor, in case Enter has been overridden somehow?

**Comment by danperks** [comment] 2023-04-10 09:38
Duplicate of #471, but will leave open as the source of the bug may be different to the other user.

**Comment by lwpassvoice** [comment] 2023-04-12 06:45
keybinding is fine
![image](https://user-images.githubusercontent.com/22510735/231373591-fb7ab06c-05ff-4509-9e60-6ee0ae083a3e.png)

**Comment by lst016** [comment] 2023-04-20 07:02
I am also unable to use the enter key to create a new line. Now I can only use Ctrl+Enter, but it only moves the cursor to a new line without creating a new line for the code.

**Comment by sgornick** [comment] 2023-04-21 15:10
In Issue #471, I describe how the "Enter is ignored" problem I encountered is the result of opening a workspace in which in ItemTable.workbench.panel.aichat.view.aichat.chatdata has in that entry:
"displayTabs": true

Hope this info helps in finding a fix for this "Enter is ignored" issue.

**Comment by jakobFNF** [comment] 2023-10-20 10:42
I will close this issue for now due to inactivity. This seems to have been fixed in an update.

![image](https://github.com/getcursor/cursor/assets/74077124/1b7eae35-3c5e-41b2-b4e2-e45126297737)

**Closed by jakobFNF** 2023-10-20 10:42 UTC
Labels: bug, question
