### ISSUE TITLE
Open from terminal

### ISSUE THREAD

**Issue by masatootake** [getcursor/cursor#53] opened 2023-03-17 08:38 UTC
I really want to open file in Cursor from terminal command. Like `code app.py` in case of VSCode.

**Comment by elanzini** [comment] 2023-03-17 12:09
duplicate of https://github.com/getcursor/cursor/issues/3

**Comment by truell20** [comment] 2023-03-18 18:29
Closing as a dup. Thanks for reporting tho!

**Closed by truell20** 2023-03-18 18:29 UTC
