### ISSUE TITLE
When copying code, multiple cursors will appear, and when pasting, there will be duplicate code on multiple ends, which is too unfriendly

### ISSUE THREAD

**Issue by qilecms** [getcursor/cursor#647] opened 2023-06-13 07:15 UTC
version:0.2.31

Mouse moves in the countryside, unable to copy entire rows

![image](https://github.com/getcursor/cursor/assets/13361784/7f39e4f3-e422-4710-b219-f7c484ceb25c)

**Comment by Sanger2000** [comment] 2023-06-17 23:58
Does this always happen when copying code? Could you take a screen recording?

**Comment by danperks** [comment] 2023-07-03 23:19
This is actually a feature, not a bug, meant for editing multiple lines at the same time. On my end at least, this happens if you hold Shift + Alt while selecting a code block. The pasting is the same thing, where it pastes at each of the cursors accidentally made. 

See here for more info: https://code.visualstudio.com/docs/getstarted/tips-and-tricks#_multi-cursor-selection:~:text=Multi%20cursor%20selection

Let us know if that seems to be what you're facing :D

**Comment by danperks** [comment] 2024-09-18 14:57
Closing as it's a feature!

**Closed by danperks** 2024-09-18 14:57 UTC
Labels: user-support
