### ISSUE TITLE
Completely hangs on renaming large files via SSH

### ISSUE THREAD

**Issue by PyroFilmsFX** [getcursor/cursor#2269] opened 2024-10-14 00:25 UTC
Title is really it.

Latest version.

This is extremly consistent, I tried renaming a 9gb mp4 and the entire software hangs with a progress bar and the file name becomes empty.

Restarts/reloads do not fix this.

**Comment by danperks** [comment] 2024-10-25 02:22
Looks like this may be an underlying issue that also affects VSCode's SSH server.
Once it's fixed in VSCode, the fix can be brought into Cursor!

Reported in this issue:
https://github.com/microsoft/vscode-remote-release/issues/4696
which is a duplicate of:
https://github.com/microsoft/vscode-remote-release/issues/1257

**Closed by danperks** 2024-10-25 02:22 UTC
