### ISSUE TITLE
A system error occurred (spawn Unknown system error -86)

### ISSUE THREAD

**Issue by icahnchen** [getcursor/cursor#1526] opened 2024-07-04 02:44 UTC
1) 
<img width="462" alt="image" src="https://github.com/getcursor/cursor/assets/8510626/d8e12712-a389-4169-9ffc-ce7e19456715">

2) MACOS Sonoma 14.5 & Cursor 0.36.0
3) Open a folder, click "Find & Replace", input some words, and the report error like 1)

**Comment by whanata** [comment] 2024-07-04 02:59
Having the same issue too for me, I tried restarting my computer and still having same issue.

**Comment by arvid220u** [comment] 2024-07-04 03:41
Does it help if you downgrade to 0.35.1? 

arm64: https://downloader.cursor.sh/builds/240621pc2f7rl8a/mac/dmg/arm64
x64: https://downloader.cursor.sh/builds/240621pc2f7rl8a/mac/dmg/x64

**Comment by arvid220u** [comment] 2024-07-04 03:45
Did this happen on previous versions? Definitely want to fix this for you.

**Comment by arvid220u** [comment] 2024-07-04 03:51
@whanata Would also be helpful to know your system details! Also MacOS Sonoma and Cursor 0.36.0? Do you have an x64 or arm64 Mac?

**Comment by arvid220u** [comment] 2024-07-04 04:20
Able to reproduce on an x64 Mac. Thank you so much for reporting! We will investigate, fix, and release a new update.

**Comment by whanata** [comment] 2024-07-04 04:25
Sorry for the late reply.

I'll wait for the new update since I'm using Brew and don't want to remove
it from Homebrew.

I'm using a Macbook Pro X64 on Mac Sonoma (14.5).

I'm just using a different editor until it's fixed (it's hard to downgrade
using Homebrew).

**Comment by icahnchen** [comment] 2024-07-04 04:40
> Did this happen on previous versions? Definitely want to fix this for you.

Of course, It works perfectly after downgrading it

**Comment by arvid220u** [comment] 2024-07-06 04:46
Fixed in 0.36.1! Thank you for reporting.

**Closed by arvid220u** 2024-07-06 04:46 UTC
