### ISSUE TITLE
Cursor Report Internal error or Failed to fetch, That's why?

### ISSUE THREAD

**Issue by jelly-oy** [getcursor/cursor#575] opened 2023-05-06 07:09 UTC
I ask a question, Cursor react Internal error, or Failed to fetch. That's why?
whether I use Cursor 0.2.8 or 0.2.9 version, the error message is the same.
<img width="473" alt="微信图片_20230506150811" src="https://user-images.githubusercontent.com/9391829/236608967-de333989-2981-4bd8-9da9-13ea143481ea.png">

**Comment by liangvim** [comment] 2023-05-06 07:13
似乎都是某国人你懂的

**Comment by jelly-oy** [comment] 2023-05-06 07:16
Do Chinese people not deserve to use Cursor?  Why? @liangvim

**Comment by reverse-2020** [comment] 2023-05-06 07:22
> Do Chinese people not deserve to use Cursor? Why? @liangvim

打开一个文件，再去chat就可以了

**Comment by liangvim** [comment] 2023-05-06 07:27
> > Do Chinese people not deserve to use Cursor? Why? @liangvim
> 
> 打开一个文件，再去chat就可以了

还是 Internal erro

**Comment by jelly-oy** [comment] 2023-05-06 07:45
> > Do Chinese people not deserve to use Cursor? Why? @liangvim
> 
> 打开一个文件，再去chat就可以了

我打开一个txt文件，Cursor依然报错：Failed to fetch

**Comment by reverse-2020** [comment] 2023-05-06 08:13
> > > Do Chinese people not deserve to use Cursor? Why? @liangvim
> > 
> > 
> > 打开一个文件，再去chat就可以了
> 
> 我打开一个txt文件，Cursor依然报错：Failed to fetch

打开它的示例py文件试试

**Comment by jelly-oy** [comment] 2023-05-06 10:12
> > > > Do Chinese people not deserve to use Cursor? Why? @liangvim
> > > 
> > > 
> > > 打开一个文件，再去chat就可以了
> > 
> > 
> > 我打开一个txt文件，Cursor依然报错：Failed to fetch
> 
> 打开它的示例py文件试试

现在又好了，可以正常输出回答，莫名奇妙的

**Comment by danperks** [comment] 2023-05-16 08:49
It's possible Cursor was facing some server errors, but as it sounds like the issue is resolved, I'll close it.
Feel free to reopen it if needed!

**Closed by danperks** 2023-05-16 08:49 UTC
