### ISSUE TITLE
The full file name cannot be displayed when the file hierarchy is too deep

### ISSUE THREAD

**Issue by light-dot** [getcursor/cursor#160] opened 2023-03-22 08:26 UTC
The full file name cannot be displayed when the file hierarchy is too deep.
For example
![image](https://user-images.githubusercontent.com/29444852/226842493-4742ff6c-cd56-4bb9-ab76-412e143e7431.png)

**Comment by danperks** [comment] 2023-03-22 21:31
Duplicate of #149

**Comment by truell20** [comment] 2023-03-23 10:06
Thanks for reporting -- Fixed in 0.1.5 :) try restarting the app to get the update

**Closed by truell20** 2023-03-23 10:06 UTC
