### ISSUE TITLE
ts language feature crash 

### ISSUE THREAD

**Issue by SunshowerC** [getcursor/cursor#1973] opened 2024-09-23 13:17 UTC
Type: <b>Performance Issue</b>

ts language feature crash  in large project. 

VS Code version: Cursor 0.41.2 (297991d169fa3a11975c5aa95adc69be73250c70, 2024-09-21T04:18:39.370Z)
OS version: Darwin x64 22.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|12, 12, 12|
|Memory (System)|32.00GB (2.76GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   22	   164	 85867	cursor main
    6	    66	 85879	   gpu-process
    0	    33	 85880	   utility-network-service
    3	   983	 85884	window [1] (Extension: TypeScript and JavaScript Language Features — monorepo)
   15	    66	 86105	shared-process
    0	    33	 86857	ptyHost
    0	     0	  2302	     /bin/bash --init-file /Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/contrib/terminal/browser/media/shellIntegration-bash.sh
    0	    33	  6497	       npm run start
    0	    66	  6512	         node /Users/bytedance/workspace/gitlab/monorepo/apps/kunlun-portal/node_modules/.bin/../../../../common/temp/node_modules/.pnpm/@rspack+cli@0.3.14-canary-12dadb2-20231120054840_mj5ut35awblgsmicfysvch3riq/node_modules/@rspack/cli/bin/rspack serve
    0	     0	  9329	     /bin/bash --init-file /Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/contrib/terminal/browser/media/shellIntegration-bash.sh
    0	     0	 88492	     /bin/bash --init-file /Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/contrib/terminal/browser/media/shellIntegration-bash.sh
   95	    33	 88214	fileWatcher [1]
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Extension: TypeScript and JavaScript Language Features — monorepo)
|    Folder (monorepo): more than 20323 files
|      File types: tsx(11185) ts(7373) json(391) md(121) local(116) js(115)
|                  hbs(93) yml(39) log(17) yaml(16)
|      Conf files:
|      Launch Configs: node(5) node-terminal;
```

</details>
<details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sql-formatter|adp|1.4.4
pyright|any|1.1.327
gallery|byt|0.6.23
thrift|cdu|0.0.1
vue-peek|dar|1.0.2
xml|Dot|2.5.1
gitlens|eam|15.5.1
auto-rename-tag|for|0.1.10
mysql-syntax|jak|1.3.1
vscode-dependency-cruiser|jua|0.0.1
intellij-idea-keybindings|k--|1.7.2
vs-color-picker|lih|1.0.0
vscode-language-pack-zh-hans|MS-|1.91.2024071009
debugpy|ms-|2024.6.0
isort|ms-|2023.10.1
python|ms-|2024.12.3
vscode-pylance|ms-|2024.8.1
remote-ssh|ms-|0.113.1
remote-ssh-edit|ms-|0.86.0
remote-explorer|ms-|0.4.3
vetur|oct|0.37.3
vscode-yaml|red|1.15.0
markdown-preview-enhanced|shd|0.8.14
vscode-todo-highlight|way|1.0.5
change-case|wma|1.0.0
local-history|xyz|1.8.1
vscode-proto3|zxh|0.5.5

</details>

**Comment by danperks** [comment] 2024-09-24 21:31
Duplicate of #1888

**Closed by danperks** 2024-09-24 21:31 UTC
