### ISSUE TITLE
AI Chat Extension causing Crash

### ISSUE THREAD

**Issue by Pradeepm98** [getcursor/cursor#2211] opened 2024-10-09 06:28 UTC
[main 2024-10-09T04:37:39.686Z] Extension host with pid 791195 exited with code: 0, signal: unknown.
[main 2024-10-09T04:38:37.442Z] [storage state.vscdb] error checking size of workbench.panel.aichat.view.aichat.chatdata: Error: Unexpected number of rows - 0
[201756:1009/113524.289209:ERROR:atom_cache.cc(229)] Add chromium/from-privileged to kAtomsToCache
Segmentation fault (core dumped)

// ubuntu

**Comment by danperks** [comment] 2024-10-10 12:55
Hi, can you provide any more info on what is happening and when does it occur?

**Comment by danperks** [comment] 2024-10-10 14:09
This looks to be a duplicate of #2212 so I'll close this for that one.
Feel free to comment in that one.

**Closed by danperks** 2024-10-10 14:09 UTC
Labels: bug, question
