### ISSUE TITLE
Sonnet 3.5 not working with OpenRouter and Cursor

### ISSUE THREAD

**Issue by PierrunoYT** [getcursor/cursor#1524] opened 2024-07-02 18:24 UTC
1) If you can, please include a screenshot of your problem
![grafik](https://github.com/getcursor/cursor/assets/95778421/5be28898-8780-4fdd-8d28-8e0636dca74f)

2) Please include the name of your operating system
Windows 11 Pro
3) If you can, steps to reproduce are super helpful

**Comment by kfwebdev** [comment] 2024-07-19 03:20
Still happening here.
![Cursor_kDp80mpEEY](https://github.com/user-attachments/assets/4fd14b1d-5c10-411e-b58a-edfbe9cef33a)
![Cursor_mqQpWwpAoR](https://github.com/user-attachments/assets/d26a1409-20f8-4b15-9d6b-e1cfc00b6405)

**Comment by alexanderatallah** [comment] 2024-08-31 04:04
This is a duplicate of https://github.com/getcursor/cursor/issues/1511

**Comment by danperks** [comment] 2024-09-18 14:23
Closing as a duplicate of #1511

**Comment by danperks** [comment] 2024-09-18 14:24
Duplicate of #1511

**Closed** 2024-09-18 14:23 UTC
