### ISSUE TITLE
internal error

### ISSUE THREAD

**Issue by JKERris** [getcursor/cursor#572] opened 2023-05-06 01:03 UTC
0.2.9 internal error

**Comment by guohenghai** [comment] 2023-05-06 01:58
me too, latest is not working on M1 macbook pro

**Comment by luckyhug** [comment] 2023-05-06 05:25
same internal error

**Comment by edg7777** [comment] 2023-05-06 08:20
me too

**Comment by WaterDropjack** [comment] 2023-05-06 08:43
me too

**Comment by yanzzchn** [comment] 2023-05-06 10:44
me too, cant  not be use , how to help me

**Comment by danperks** [comment] 2023-05-16 08:52
Seems like a duplicate of #571 and #570.
Assuming the server was down, and is resolved now.

**Closed by danperks** 2023-05-16 08:52 UTC
Labels: bug
