### ISSUE TITLE
In my environment, I cannot directly connect to the internet. How can I set up a proxy for the software?

### ISSUE THREAD

**Issue by Runbacktoo** [getcursor/cursor#381] opened 2023-03-30 06:02 UTC

**Comment by danperks** [comment] 2023-04-10 18:45
The latest version of Cursor, since v0.2.0, is based upon VSCodium and therefore has alot of the same features. If you can, give this a try and see if everything still functions as expected:
https://code.visualstudio.com/docs/setup/network

**Comment by danperks** [comment] 2023-04-10 20:02
This is a duplicate of #128, and more discussion has occurred there, so I'll close this issue in favour for that one. 😄

**Closed by danperks** 2023-04-10 20:02 UTC
Labels: bug, help wanted, question
