### ISSUE TITLE
My editor's enter is disabled

### ISSUE THREAD

**Issue by HXSlimeng** [getcursor/cursor#471] opened 2023-04-07 08:45 UTC
since i update to version 0.2.1,i can't click enter to wrap
maybe it is conflict with plugins ,when i delete all the cursor profile , it is going right

**Comment by HXSlimeng** [comment] 2023-04-07 08:46
ctrl + enter is no problem

**Comment by truell20** [comment] 2023-04-08 06:45
could you send a screenshot or screen recording of where this happens?

**Comment by danperks** [comment] 2023-04-10 09:38
Duplicate of #480, but will leave open as the source of the bug may be different to the other user.

**Comment by CodesAreHonest** [comment] 2023-04-13 05:13
I am using Intel Mac, do not possess any Enter keybindings that conflicts in my Cursor IDE and confirm that the Enter key is not working.

**Comment by HXSlimeng** [comment] 2023-04-13 07:22
I‘m sure that i encountered the problem，sorry about that i cant reproduce this issue，the plugins i was installed included Volar and some vscode themes，hope it can help you

**Comment by sgornick** [comment] 2023-04-14 20:34
I've had this several times, including at this moment in time.  There doesn't seem to be any trigger event that I can tell.  Just routine activity and all of a sudden, the Enter key stops behaving as normal in the editor.  The Enter key in editor is completely ignored.  In the Generate dialog (Ctrl-K), Enter triggers execute of the prompt, as is normal.  Same for the Chat pane (Ctrl-L), Enter there works as well.

I can reset with brute-force by removing entire AppData/Roaming/Cursor.  But then I lose my config and start as if I had done a new install, so I would like to know what is the root cause and resolution, and thus I won't lose my configuration each time.

The only extension I've installed is Python, I believe.  Will proceed after doing the brute-force reset and then will keep better notes to see if there is anything that might indicate a trigger.  Will likely hit it again within a few days., if past experience with this continues on repeat.

**Comment by sgornick** [comment] 2023-04-14 22:34
OK, I think I figured out what is going on.   When the application launches, the cursor is sitting in the "Chat about the current code file" (as if that was the state when I closed the editor, perhaps?).

I can click in my .txt file open, for instance, and Enter is ignored.  Ctrl-Enter behaves as expected, but Enter is ignored.

I can close the workspace and open a different one, and the Enter there works fine.   So it is related to this one workspace.  I can even reload the problem workspace and the "Enter ignored" issue returns.  

I then closed the app and deleted the AppData\Roaming\Cursor\User\workspaceStorage\[guid] for the problem workspace, then re-launched the app and I could re-open the .txt file and Enter works fine.

I also learned, after restoring the directory, that I only needed to click on the Chats icon (clock / rewind type icon), and that would do something that would change the state, and from there I could use Enter in my .txt file again, without deleting anything.

I have archived the entire AppData\Roaming\Cursor directory and can restore to the "Enter ignored" state on demand, for further troubleshooting if this does not provide enough clues to identify the root cause.

**Comment by danperks** [comment] 2023-04-15 08:32
Sounds like something for deeper investigation @truell20

**Comment by meguoe** [comment] 2023-04-17 03:33
me too

**Comment by sgornick** [comment] 2023-04-17 04:22
> me too

You might be able to help confirm a workaround I found to when this happened to me. 

Is this occurring with just one workspace?  i.e., if you open a new workspace, or open a different workspace, does that "Enter ignored" issue occur there as well?

Either way, when you find the "Enter ignored" issue, Would you mind trying this?  Click on the Chats icon (the icon in the top right with the clock + rewind  icon).

Does doing that suddenly free up your Enter key?

Also, I see Cursor v0.2.3 was released.  I won't be at the computer where I had the issue until later Monday, but I will be checking to see if opening a workspace with this issue (but in v0.2.3) has any different result.

**Comment by lionkk** [comment] 2023-04-19 03:15
> OK, I think I figured out what is going on. When the application launches, the cursor is sitting in the "Chat about the current code file" (as if that was the state when I closed the editor, perhaps?).
> 
> I can click in my .txt file open, for instance, and Enter is ignored. Ctrl-Enter behaves as expected, but Enter is ignored.
> 
> I can close the workspace and open a different one, and the Enter there works fine. So it is related to this one workspace. I can even reload the problem workspace and the "Enter ignored" issue returns.
> 
> I then closed the app and deleted the AppData\Roaming\Cursor\User\workspaceStorage[guid] for the problem workspace, then re-launched the app and I could re-open the .txt file and Enter works fine.
> 
> I also learned, after restoring the directory, that I only needed to click on the Chats icon (clock / rewind type icon), and that would do something that would change the state, and from there I could use Enter in my .txt file again, without deleting anything.
> 
> I have archived the entire AppData\Roaming\Cursor directory and can restore to the "Enter ignored" state on demand, for further troubleshooting if this does not provide enough clues to identify the root cause.

Thanks for sharing. I had the same problem, and fixed it now.

**Comment by sgornick** [comment] 2023-04-21 15:07
I am able to confirm that this issue persists with v0.2.7, at least when trying to open a workspace where the "enter ignored" issue had previously been encountered.

I dug a little further.

The only difference in that workspace's database (workspaceStorage) that results from clicking on the Chats icon  (the icon in the top right with the clock + rewind icon) is that in the json for the ItemTable.workbench.panel.aichat.view.aichat.chatdata there is an entry:
"displayTabs": true

Simply setting that to false permits the Enter key to resume being recognized.

I'm not sure what had set this to true, but it appears that in any workspace, simply setting this displayTabs to true will introduce this same "Enter ignored" behavior in that workspace as well.

I don't know if Cursor is supposed to properly accommodate this "displayTabs: true" scenario, but  today, that will result in the Enter key to be ignored.

**Closed** 2023-04-25 01:31 UTC
Labels: bug, question
