### ISSUE TITLE
TS server crashed

### ISSUE THREAD

**Issue by arthur-da-1205** [getcursor/cursor#1966] opened 2024-09-23 04:25 UTC
Type: <b>Bug</b>

Cannot restart TS Server

VS Code version: Cursor 0.40.4 (63dae81aea2c3fc079420fe72578a8eef26ba870, 2024-09-05T02:52:05.660Z)
OS version: Darwin x64 19.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2500)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|12, 8, 6|
|Memory (System)|16.00GB (1.42GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
catppuccin-vsc|Cat|3.15.2
vscode-eslint|dba|3.0.10
es7-react-js-snippets|dsz|4.4.3
bracket-pair-toggler|dzh|0.0.3
gitlens|eam|15.5.1
prettier-vscode|esb|11.0.0
auto-close-tag|for|0.5.15
auto-rename-tag|for|0.1.10
todo-tree|Gru|0.0.226
beautify|Hoo|1.5.0
dotenv|mik|1.0.1
color-highlight|nau|2.8.0
material-icon-theme|PKi|5.11.1
prisma|Pri|5.19.1
vs-code-prettier-eslint|rve|6.0.0
autoimport|ste|1.5.4
vscode-stylelint|sty|1.4.0
html-css-class-completion|Zig|1.20.0

(1 theme extensions excluded)

</details>

**Comment by danperks** [comment] 2024-09-24 21:35
Duplicate of #1888

**Closed by danperks** 2024-09-24 21:35 UTC
