### ISSUE TITLE
if possible, please add font settings, and more optional config...

### ISSUE THREAD

**Issue by GmwEnterprise** [getcursor/cursor#131] opened 2023-03-21 05:25 UTC

**Comment by FINALxxx** [comment] 2023-03-21 05:31
agree

**Comment by PlutoOfCharon** [comment] 2023-03-21 05:46
agree

**Comment by ajavaer** [comment] 2023-03-21 06:25
agree +1

**Comment by Fire-** [comment] 2023-03-22 02:59
dupe of #103

**Comment by truell20** [comment] 2023-04-08 07:45
Should be fixed in newest version 🙂

**Closed by truell20** 2023-04-08 07:45 UTC
