### ISSUE TITLE
Make cursor be able to read PDF in the folder.

### ISSUE THREAD

**Issue by Am0stafa** [getcursor/cursor#1565] opened 2024-07-25 19:03 UTC
When I mention any PDF it ignores it
![Screenshot 2024-07-25 at 9 46 22 PM](https://github.com/user-attachments/assets/3c3cad23-de09-4b8a-86d5-44f9872f7de0)

**Comment by danperks** [comment] 2024-09-24 21:20
Duplicate of #1894

**Closed by danperks** 2024-09-24 21:20 UTC
