### ISSUE TITLE
Sometimes the code will be truncated so that it can continue is not in the code format

### ISSUE THREAD

**Issue by LexZhang16** [getcursor/cursor#94] opened 2023-03-19 02:47 UTC
Tell it to keep writing and it prints the code in the wrong format, just to keep writing from the previous function

**Comment by zhaohai1024** [comment] 2023-03-19 02:56
+1

**Comment by truell20** [comment] 2023-03-19 19:34
Agree! Thanks for reporting. Going to close this as a duplicate of #96

**Closed by truell20** 2023-03-19 19:34 UTC
