### ISSUE TITLE
Don't require a login for free usage

### ISSUE THREAD

**Issue by hades200082** [getcursor/cursor#2013] opened 2024-09-27 08:52 UTC
**Describe the solution you'd like**
When trying to trial Cursor it seems that it requires a login to make use of AI features - the entire USP of the IDE. 

Requiring a login for me to try it out puts me off. I don't want to give out my details just to try something - if I choose to go on to a paid plan, that's different but the free plan shouldn't require a login.

**Comment by danperks** [comment] 2024-10-02 19:48
Hi, I appreciate the notion, I too prefer a free trial without having to hand over my details. The issue is with avoid abuse.

By having an account, it means the free usage can be limited to avoid users abusing the free limits that Cursor allows. The goal of the free usage is to let people try Cursor before they buy, which in the world of software is often hard to come by.

Without an account, people could use a VPN to change their IP and bypass any usage limits Cursor have put in. If they gave free, unlimited access to everyone, they'd never pay their own salaries!

As with any online platform, you can opt to delete your account if you don't want it anymore, but an account will likely remain necessary to use Cursor's free tier.

I'll close this for now, but feel free to comment further if you have any questions and I can reopen this if you want a discussion or to raise a suggestion on how else you'd like the free tier to work.

**Closed by danperks** 2024-10-02 19:48 UTC
