### ISSUE TITLE
can't open cursor in ubuntu 22.04

### ISSUE THREAD

**Issue by cyxinda** [getcursor/cursor#135] opened 2023-03-21 09:46 UTC
my ubuntu version is :
```bash
root@ubuntu:/home/cyxinda/Downloads# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy
```
I open cursor-0.1.3 and error log is as follow:
```bash
root@ubuntu:/home/cyxinda/Downloads# ./Cursor-0.1.3.AppImage -appimage-extract --no-sandbox
[1443435:0321/173422.542511:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[1443435:0321/173422.542650:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
[1443533:0321/173422.700926:ERROR:angle_platform_impl.cc(43)] Display.cpp:1004 (initialize): ANGLE Display::initialize error 12289: Could not open the default X display.
ERR: Display.cpp:1004 (initialize): ANGLE Display::initialize error 12289: Could not open the default X display.
[1443533:0321/173422.701108:ERROR:gl_display.cc(508)] EGL Driver message (Critical) eglInitialize: Could not open the default X display.
[1443533:0321/173422.701202:ERROR:gl_display.cc(920)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
Authorization required, but no authorization protocol specified
[1443533:0321/173422.702601:ERROR:angle_platform_impl.cc(43)] Display.cpp:1004 (initialize): ANGLE Display::initialize error 12289: Could not open the default X display.
ERR: Display.cpp:1004 (initialize): ANGLE Display::initialize error 12289: Could not open the default X display.
[1443533:0321/173422.702713:ERROR:gl_display.cc(508)] EGL Driver message (Critical) eglInitialize: Could not open the default X display.
[1443533:0321/173422.702819:ERROR:gl_display.cc(920)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[1443533:0321/173422.702924:ERROR:gl_ozone_egl.cc(23)] GLDisplayEGL::Initialize failed.
[1443533:0321/173422.740236:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[1443435:0321/173422.953120:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
17:34:22.963 › Made main window
[1443435:0321/173423.037028:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
17:34:23.037 › setting up handle get_folder
17:34:23.038 › setting up handle getClipboard
17:34:23.038 › setting up handle get_file
17:34:23.039 › ---------------------first one 0
17:34:23.058 › -------------error
17:34:23.059 › Error: Command failed: command -v zsh
    at checkExecSyncError (node:child_process:865:11)
    at Object.execSync (node:child_process:936:15)
    at Object.execSync (node:electron/js2c/asar_bundle:2:12709)
    at /tmp/.mount_CursorqTForZ/resources/app.asar/.webpack/main/index.js:8:884962
    at App.<anonymous> (/tmp/.mount_CursorqTForZ/resources/app.asar/.webpack/main/index.js:8:885311)
    at App.emit (node:events:525:35)
17:34:23.065 › ---------------------first one 1
17:34:23.089 › -------------after
17:34:23.090 › setting up index
17:34:23.091 › setup index
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
[1443570:0321/173423.140497:ERROR:angle_platform_impl.cc(43)] Display.cpp:1004 (initialize): ANGLE Display::initialize error 12289: Could not open the default X display.
ERR: Display.cpp:1004 (initialize): ANGLE Display::initialize error 12289: Could not open the default X display.
[1443570:0321/173423.140698:ERROR:gl_display.cc(508)] EGL Driver message (Critical) eglInitialize: Could not open the default X display.
[1443570:0321/173423.140788:ERROR:gl_display.cc(920)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
Authorization required, but no authorization protocol specified
[1443570:0321/173423.141193:ERROR:angle_platform_impl.cc(43)] Display.cpp:1004 (initialize): ANGLE Display::initialize error 12289: Could not open the default X display.
ERR: Display.cpp:1004 (initialize): ANGLE Display::initialize error 12289: Could not open the default X display.
[1443570:0321/173423.141299:ERROR:gl_display.cc(508)] EGL Driver message (Critical) eglInitialize: Could not open the default X display.
[1443570:0321/173423.141423:ERROR:gl_display.cc(920)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[1443570:0321/173423.141523:ERROR:gl_ozone_egl.cc(23)] GLDisplayEGL::Initialize failed.
[1443570:0321/173423.144243:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
[1443581:0321/173423.209425:ERROR:angle_platform_impl.cc(43)] DisplayVkXcb.cpp:59 (initialize): xcb_connect() failed, error 1
ERR: DisplayVkXcb.cpp:59 (initialize): xcb_connect() failed, error 1
[1443581:0321/173423.209613:ERROR:angle_platform_impl.cc(43)] Display.cpp:1004 (initialize): ANGLE Display::initialize error 12289: Not initialized.
ERR: Display.cpp:1004 (initialize): ANGLE Display::initialize error 12289: Not initialized.
[1443581:0321/173423.209725:ERROR:gl_display.cc(508)] EGL Driver message (Critical) eglInitialize: Not initialized.
[1443581:0321/173423.209823:ERROR:gl_display.cc(920)] eglInitialize SwANGLE failed with error EGL_NOT_INITIALIZED
[1443581:0321/173423.209925:ERROR:gl_ozone_egl.cc(23)] GLDisplayEGL::Initialize failed.
[1443581:0321/173423.212619:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
[1443590:0321/173423.224727:ERROR:gpu_init.cc(523)] Passthrough is not supported, GL is disabled, ANGLE is 
[1443590:0321/173423.244303:ERROR:x11_software_bitmap_presenter.cc(142)] XGetWindowAttributes failed for window 20971523
17:34:25.024 › found settings
17:34:25.068 › STORING SETTINGS
17:34:25.069 › {
  keyBindings: 'none',
  useFour: 'disabled',
  contextType: 'none',
  textWrapping: 'disabled'
}
17:34:25.071 › that was the settings
17:34:25.134 › starting server for copilot
17:34:25.135 › Store has language copilot {
  name: 'copilot',
  running: true,
  downloadedInfo: {
    isNode: true,
    command: '/tmp/.mount_CursorlQ1FxZ/resources/lsp/copilot/dist/agent.js',
    args: []
  }
}
17:34:25.175 › !!!!!!!!!Finished spawning child process copilot
17:34:25.179 › created connection copilot
17:34:25.350 › lang copilot stderr: node:internal/modules/cjs/loader:966
  throw err;
  ^

Error: Cannot find module '/tmp/.mount_CursorlQ1FxZ/resources/lsp/copilot/dist/agent.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:963:15)
    at Module._load (node:internal/modules/cjs/loader:811:27)
    at f._load (node:electron/js2c/asar_bundle:2:13328)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

how I can make it?

**Comment by jkxiongxin** [comment] 2023-03-22 05:07
It looks like you're trying to run cursor as the root user. I tried this, it's useful for me，to grant the root user access to the X server. Run the following command in a terminal under your regular user account:
xhost +SI:localuser:root

**Comment by gyz233** [comment] 2023-03-23 05:36
run
chmod u+x Cursor-0.1.3.AppImage
first

**Comment by Drreeww** [comment] 2023-03-25 01:58
same error reproduct on Kylin V10 SP1, chmod u+x can not solve this.

**Comment by truell20** [comment] 2023-04-08 07:48
Can you open the newest version on Ubuntu?

**Comment by danperks** [comment] 2023-04-14 20:09
As this may be fixed in the new version, and seems to be a duplicate of #97, I'll close this for now.

**Closed** 2023-04-14 20:10 UTC
Labels: bug, question
