### ISSUE TITLE
mac更新后，无法正常使用！

### ISSUE THREAD

**Issue by is-ZYL** [getcursor/cursor#469] opened 2023-04-07 06:32 UTC
版本信息：
```text

版本: 0.2.0
提交: 72bf0113753c0c51eb3454a37bedc442dd109699
日期: 2023-04-06T01:40:20.726Z
Electron: 19.1.9
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 21.5.0
沙盒化: No

```

<img width="617" alt="image" src="https://user-images.githubusercontent.com/39947605/230554173-fbec86a8-017f-4ea1-8741-00503afa4d15.png">

**Comment by is-ZYL** [comment] 2023-04-07 06:40
> "Cannot read properties of undefined (reading 'uri')" <img alt="image" width="917" src="https://user-images.githubusercontent.com/53255743/230531229-6a78e184-963c-4f63-ac65-f25ec00df518.png">

**Comment by zhangruolin** [comment] 2023-04-07 06:58
me too

**Comment by Devil-muhan** [comment] 2023-04-07 08:09
me too

**Comment by sungongwei** [comment] 2023-04-07 08:13
[https://github.com/getcursor/cursor/issues/455#issuecomment-1499038709](url)

**Comment by sungongwei** [comment] 2023-04-07 08:14
[](https://github.com/getcursor/cursor/issues/455#issuecomment-1499038709)

**Comment by mowenbole** [comment] 2023-04-07 09:20
me too

![image](https://user-images.githubusercontent.com/24892915/230582800-7c9d7a74-d683-49b0-ad26-e0c73273342b.png)

**Comment by baixiangdagumian** [comment] 2023-04-07 09:23
me too

**Comment by renyuntao** [comment] 2023-04-07 09:34
me too

**Comment by Sanger2000** [comment] 2023-04-10 03:48
Hey, this should be resolved in the newest version! If not, try opening a file/folder, and it should work

**Comment by Lax-Asuna** [comment] 2023-04-10 05:37
I have the same question with the newest version on mac

**Comment by hzr1140521792** [comment] 2023-04-10 06:14
me too

**Comment by danperks** [comment] 2023-04-10 10:03
Duplicate of #455

**Comment by JS-mark** [comment] 2023-04-12 02:28
我是直接闪退

**Comment by jakobFNF** [comment] 2023-10-20 14:37
I will close this issue for now due to inactivity. Cursor has undergone significant updates since then. If this issue still persists for you, please open another issue!

**Closed by jakobFNF** 2023-10-20 14:37 UTC
Labels: bug, duplicate
