### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by liulian701** [getcursor/cursor#570] opened 2023-05-05 08:35 UTC
system:windows7
While the brower shows"You may now proceed back to Cursor", however the Cursor  stays in the 'sign in' interface. 
So when I chat with cursor ,it tells me 'failed  to fetch'.  
Same to issue #490 and #507

**Comment by danperks** [comment] 2023-05-16 08:53
Seems to be a duplicate of #571 and #572.
Assuming this was a server error that's resolved now.

**Closed by danperks** 2023-05-16 08:53 UTC

**Comment by KunShanJiaTi** [comment] 2023-05-27 09:57
same question. any solution?

**Comment by Edwardp17** [comment] 2023-10-10 22:10
Hey all, im having this issue today on macOS, any solutions?
