### ISSUE TITLE
C Language Server can't install

### ISSUE THREAD

**Issue by yuptse** [getcursor/cursor#126] opened 2023-03-20 16:50 UTC
Hello, I have run into a problem that prevents me from starting the C language service. I am using Windows 11 and have installed the latest version of VSCode. I have also installed clang, clangd, gcc, llvm and other tools through Msys2 and added their paths to the system variables. What else should I do to get the C language service working? Thank you.

**Comment by Climber2** [comment] 2023-03-21 01:06
me too

**Comment by hjliu-cool** [comment] 2023-03-21 06:41
same

**Comment by Fire-** [comment] 2023-03-22 03:17
duplicate of #20

**Comment by truell20** [comment] 2023-04-08 07:44
Should be fixed in newest version 🙂

**Closed by truell20** 2023-04-08 07:44 UTC
