### ISSUE TITLE
Easier way to open folders

### ISSUE THREAD

**Issue by Air1996** [getcursor/cursor#1823] opened 2024-09-05 02:48 UTC
**Is your feature request related to a problem? Please describe.**
Support for dragging and dropping files and folders onto the dock icon to open them on macOS, like vscode does

**Comment by marcellocurto** [comment] 2024-09-06 07:27
Yes, please add this! One of the first things I noticed when trying out Cursor.

**Comment by pasqualevitiello** [comment] 2024-09-21 10:41
yeah, add this feature please!

**Comment by danperks** [comment] 2024-10-02 19:38
Duplicate of #586

**Closed by danperks** 2024-10-02 19:38 UTC
