### ISSUE TITLE
Want to show git diff notification badge like this 

### ISSUE THREAD

**Issue by keigo9** [getcursor/cursor#2025] opened 2024-09-29 05:57 UTC
![スクリーンショット 2024-09-29 14 39 03](https://github.com/user-attachments/assets/38bf28f0-9b1e-4948-90a8-b5956ed66733)

**Comment by danperks** [comment] 2024-10-03 22:15
Duplicate of #2136
That bug has a better description, so opting to use that as the one to keep open.

**Closed** 2024-10-03 22:16 UTC
