### ISSUE TITLE
[Feature Request] Add Remote Tunnel Access from VSCode

### ISSUE THREAD

**Issue by kingwe-stack** [getcursor/cursor#1877] opened 2024-09-12 04:07 UTC
<img width="978" alt="image" src="https://github.com/user-attachments/assets/f6a6aa3a-1d40-4828-90e6-e9ebe03fccb5">
do not exist this button

**Comment by danperks** [comment] 2024-09-18 14:25
Hi, this is a VSCode only feature, and is not available within Cursor.

**Comment by cmosguy** [comment] 2024-11-04 14:24
@danperks  will this ever be a Cursor feature, why can we not have this?

**Comment by danperks** [comment] 2024-11-04 14:26
Hi @cmosguy,

There's been a much longer discussion in #1191 which may have a workaround for you.
I'm hoping to figure more out soon regarding if we can make this a full Cursor feature!

I'll close this as a duplicate of #1191

**Closed by danperks** 2024-11-04 14:26 UTC
Labels: enhancement
