### ISSUE TITLE
The normal chat has a maximum output of 3,945 tokens which is very low make it not less than 10k tokens

### ISSUE THREAD

**Issue by Am0stafa** [getcursor/cursor#1694] opened 2024-08-26 11:11 UTC
1) If you can, please include a screenshot of your problem
2) Please include the name of your operating system
3) If you can, steps to reproduce are super helpful

**Comment by danperks** [comment] 2024-09-24 21:19
Duplicate of #1670

**Closed by danperks** 2024-09-24 21:19 UTC
