### ISSUE TITLE
Drag and Drop Directory to Cursor Icon to Open Directory Not Working

### ISSUE THREAD

**Issue by lasharela** [getcursor/cursor#2343] opened 2024-11-05 02:43 UTC
Description:

On macOS, in Visual Studio Code, you can drag and drop a directory onto the VSC icon, and it opens the directory in a new window. However, attempting the same action with the cursor icon does not work as expected. Dragging a directory to the cursor icon does not trigger the directory to open.

Steps to Reproduce:

	1.	Open Visual Studio Code on macOS.
	2.	Attempt to drag a directory from Finder to the cursor icon.

Expected Behavior:
The directory should open within Visual Studio Code as it does when dropping the directory onto the VSC icon.

Actual Behavior:
The directory does not open when dropped on the cursor icon.

Additional Context:

	•	macOS version: Sonoma 14.5
	•	Cursor: 0.42

**Comment by danperks** [comment] 2024-11-07 13:52
Hey, this isn't a feature of Cursor right now, but it's a popular request so you may see it in a new release soon!

Duplicate of #586

**Closed by danperks** 2024-11-07 13:52 UTC
